# Generated by Django 3.0.7 on 2020-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('core', '0004_touristspot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
